INSERT INTO modes VALUES (1, 'test-setup', 1, NULL, NULL), (2, 'test-sik', 1, NULL, NULL), (3, 'real', 0, NULL, NULL);
UPDATE modules SET pos = pos + 3 WHERE pos >= 1;
INSERT INTO modules (name, loaded, dashboard, menu, parent, classname, pos, icon, color) VALUES ('elections', 1, 1, 1, '', '\modules\tcontrol\elections\ElectionsController', 1, 'calendar', 'teal');
INSERT INTO modules (name, loaded, dashboard, menu, parent, classname, pos, icon, color) VALUES ('modes', 1, 1, 1, '', '\modules\tcontrol\modes\ModesController', 2, 'cogs', 'purple');
INSERT INTO modules (name, loaded, dashboard, menu, parent, classname, pos, icon, color) VALUES ('siks', 1, 1, 1, '', '\modules\tcontrol\siks\SiksController', 3, 'landmark', 'red');
INSERT INTO miks (name) VALUES ('Благоевград');
INSERT INTO miks (name) VALUES ('Бургас');
INSERT INTO miks (name) VALUES ('Варна');
INSERT INTO miks (name) VALUES ('Велико Търново');
INSERT INTO miks (name) VALUES ('Видин');
INSERT INTO miks (name) VALUES ('Враца');
INSERT INTO miks (name) VALUES ('Габрово');
INSERT INTO miks (name) VALUES ('Добрич');
INSERT INTO miks (name) VALUES ('Кърджали');
INSERT INTO miks (name) VALUES ('Кюстендил');
INSERT INTO miks (name) VALUES ('Ловеч');
INSERT INTO miks (name) VALUES ('Монтана');
INSERT INTO miks (name) VALUES ('Пазарджик');
INSERT INTO miks (name) VALUES ('Перник');
INSERT INTO miks (name) VALUES ('Плевен');
INSERT INTO miks (name) VALUES ('Пловдив Град');
INSERT INTO miks (name) VALUES ('Пловдив Област');
INSERT INTO miks (name) VALUES ('Разград');
INSERT INTO miks (name) VALUES ('Русе');
INSERT INTO miks (name) VALUES ('Силистра');
INSERT INTO miks (name) VALUES ('Сливен');
INSERT INTO miks (name) VALUES ('Смолян');
INSERT INTO miks (name) VALUES ('София 23 МИР');
INSERT INTO miks (name) VALUES ('София 24 МИР');
INSERT INTO miks (name) VALUES ('София 25 МИР');
INSERT INTO miks (name) VALUES ('София Област');
INSERT INTO miks (name) VALUES ('Стара Загора');
INSERT INTO miks (name) VALUES ('Търговище');
INSERT INTO miks (name) VALUES ('Хасково');
INSERT INTO miks (name) VALUES ('Шумен');
INSERT INTO miks (name) VALUES ('Ямбол');