#!/usr/bin/env php
<?php

/**
 * This script will clean all unused files generated by the system (for example when a user uploads a file but does not
 * save the form).
 * The script works by:
 * 1) gathering all used file IDs:
 * 1.1) in tables related (foreign key) to the uploads table
 * 1.2) other well-known fields in all DB tables named 'image', 'images', 'file', 'files', 'upload', 'uploads' (those
 *      fields are always treated like CSV - upload IDs separated by comma)
 * 1.3) all varchar and text columns are scanned for links to upload/ID and the ID is extracted
 * 2) then the uploads table is traversed row by row and all files uploaded more than 24 hours ago, which are not in
 *    the used list (gathered in step 1) are DELETEd from the uploads table and the file is deleted from the
 *    file system
 *
 * If disk usage is an issue - execute once a day in a low proprity, for example:
 * 0 4 * * * cleanfiles.php > /dev/null
 */

declare(strict_types=1);

require_once __DIR__ . '/../bootstrap.php';

\helpers\Jobs::cleanfiles();

echo 'DONE' . "\r\n";
exit(0);
